language: java
jdk: openjdk8
branches:
  only:
  - master
  - "/.*-[0-9]+\\..*/"
install: true
script: ".travis/build.sh"
env:
  global:
  - secure: ZU9NXWq+6k9jWa9ZeeO7VSf0yrJs5zhp2zEOjeAo8WH3T+qxh8Ye4yJEgzeYQMmSo92sF8hqlhnQlUZBb0h/nkKWaSKqWCNZAPJ2qISyo0k0MCizDWAi+WQIw6ntYB4i5LjkU5GkxVxq/Rg7OETFVnhrdsymbu5lCarJks6KZuY=
  - secure: RQkJArxl/y7TuNapvUT5d2YBrL4f6XBZQbtGVFyZS/Q+mFNg3YLhhnIc1Gzn7x26sGCkvFZie52MHG1SbVI4WcYqO3Xpq9idrbCLPZ4QiO0+eW51DjwWaRPgwuI462upDLmvz0kl2TGvgvCX7wzPig5BDRrDu9W3tRpgVuH3LrA=
